version: '3.7'

services:
  app:
    build: ./api/app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api/app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=sparknet
      - POSTGRES_PASSWORD=sparknet
      - POSTGRES_DB=sparknet_dev

volumes:
  postgres_data: